FROM python:3.10-slim

RUN apt update && apt install -y \
    ffmpeg \
    libsndfile1 \
    libgl1 \
    && apt clean

WORKDIR /app

COPY requirements.api.txt .
RUN pip install --no-cache-dir -r requirements.api.txt

COPY . .

EXPOSE 8000
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
